### ISSUE TITLE
Does it support ACO Version 1?

### ISSUE THREAD

**Issue by diuming** [frenetisch-applaudierend/acokit#1]
It's good tool for ACO.
as title, 
Does it support ACO Version 1?
thx.

[PANTONE+ Solid Coated-V3.aco.zip](https://github.com/frenetisch-applaudierend/acokit/files/6269161/PANTONE%2B.Solid.Coated-V3.aco.zip)

**Comment by frenetisch-applaudierend** [comment]
Hi diuming, thank you for the kind words. It's a very old project of mine and not actively maintained anymore. But looking over the source code it should indeed support ACO V1.

**Comment by diuming** [comment]
@frenetisch-applaudierend thanks for reply.

I try to transfer your code to Swift version.
But, I stuck in entry name of AEO Version1.
I can get correct any type of color data(reference by your code), but can't get color name.
thx.

**Comment by diuming** [comment]
@frenetisch-applaudierend I find the key issue. `stream.hasBytesAvailable`
I still confuse, Why I need to perform twice loops to get color name and data(ACO V1)?
thx.

**Comment by frenetisch-applaudierend** [comment]
It's good to see it evolve even after this time :-)

It has been a long time, and I'm not 100% sure about all details anymore. But from what I remember, the v1 and v2 are in separate parts in the data stream, and they need to be combined. So first v1 is read, and then checked if there is v2 data as well.

**Comment by frenetisch-applaudierend** [comment]
This could be helpful: https://medium.com/swlh/mastering-adobe-color-file-formats-d29e43fde8eb
